# Generated by Django 4.2.6 on 2023-10-28 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='prix',
            field=models.IntegerField(default=2500),
            preserve_default=False,
        ),
    ]
