# Generated by Django 4.2.6 on 2023-10-28 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_article_prix'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='titre',
            new_name='nom',
        ),
    ]
